wandb_version: 1

_content:
  desc: null
  value:
    callbacks: '{''model_checkpoint'': {''_target_'': ''lightning.pytorch.callbacks.ModelCheckpoint'',
      ''dirpath'': ''${paths.output_dir}/checkpoints'', ''filename'': ''epoch_{epoch:03d}'',
      ''monitor'': ''val_loss'', ''verbose'': False, ''save_last'': True, ''save_top_k'':
      3, ''mode'': ''min'', ''auto_insert_metric_name'': False, ''save_weights_only'':
      False, ''every_n_train_steps'': None, ''train_time_interval'': None, ''every_n_epochs'':
      None, ''save_on_train_epoch_end'': None}, ''early_stopping'': {''_target_'':
      ''lightning.pytorch.callbacks.EarlyStopping'', ''monitor'': ''val_loss'', ''min_delta'':
      0.0, ''patience'': 300, ''verbose'': False, ''mode'': ''min'', ''strict'': True,
      ''check_finite'': True, ''stopping_threshold'': None, ''divergence_threshold'':
      None, ''check_on_train_epoch_end'': None}, ''model_summary'': {''_target_'':
      ''lightning.pytorch.callbacks.RichModelSummary'', ''max_depth'': -1}, ''rich_progress_bar'':
      {''_target_'': ''lightning.pytorch.callbacks.RichProgressBar''}}'
    ckpt_path: D:/motion-tokenizer/logs/train/runs/2024-07-25_15-12-57/checkpoints/epoch_003.ckpt
    data: '{''_target_'': ''src.data.gesture_datamodule.MotionDataModule'', ''dataset_name'':
      ''beat'', ''motion_type'': ''bvh'', ''test_dir'': ''new_data/lmdb_test'', ''train_dir'':
      ''new_data/lmdb_train'', ''val_dir'': ''new_data/lmdb_val'', ''batch_size'':
      1, ''num_workers'': 0, ''pin_memory'': False, ''n_poses'': 128, ''n_preposes'':
      32, ''n_joints'': 73, ''pose_dim'': 657, ''motion_fps'': 15, ''raw_data_path'':
      ''${paths.data_dir_test}'', ''data_norm_stat_path'': ''data/motion_data_stat.npy'',
      ''normalization_method'': ''mean-std'', ''use_weighted_sampler'': False}'
    extras: '{''ignore_warnings'': False, ''enforce_tags'': True, ''print_config'':
      True}'
    logger: '{''csv'': {''_target_'': ''lightning.pytorch.loggers.csv_logs.CSVLogger'',
      ''save_dir'': ''${paths.output_dir}'', ''name'': ''csv/'', ''prefix'': ''''},
      ''tensorboard'': {''_target_'': ''lightning.pytorch.loggers.tensorboard.TensorBoardLogger'',
      ''save_dir'': ''${paths.output_dir}/tensorboard/'', ''name'': None, ''log_graph'':
      False, ''default_hp_metric'': True, ''prefix'': ''''}, ''wandb'': {''_target_'':
      ''lightning.pytorch.loggers.wandb.WandbLogger'', ''save_dir'': ''${paths.output_dir}'',
      ''offline'': False, ''id'': None, ''anonymous'': None, ''project'': ''motion-tokenizer'',
      ''log_model'': False, ''prefix'': '''', ''group'': '''', ''tags'': [], ''job_type'':
      ''''}}'
    model: '{''_target_'': ''src.models.vae_module.VQVaeLitModel'', ''nfeats'': ''${data.pose_dim}'',
      ''quantizer'': ''ema_reset'', ''code_num'': 256, ''code_dim'': 512, ''output_emb_width'':
      512, ''down_t'': 3, ''stride_t'': 2, ''width'': 512, ''depth'': 3, ''dilation_growth_rate'':
      3, ''norm'': ''None'', ''activation'': ''relu'', ''normalization_method'': ''${data.normalization_method}'',
      ''data_norm_stat_path'': ''${data.data_norm_stat_path}'', ''recons_loss'': ''l1_smooth'',
      ''nb_joints'': ''${data.n_joints}'', ''commit'': 0.02, ''loss_vel_factor'':
      0.5, ''optimizer_cfg'': {''target'': ''torch.optim.AdamW'', ''params'': {''lr'':
      0.0002, ''betas'': [0.9, 0.99], ''weight_decay'': 0.0}}, ''scheduler_cfg'':
      {''target'': ''torch.optim.lr_scheduler.CosineAnnealingLR'', ''params'': {''T_max'':
      100, ''eta_min'': 1e-06}}}'
    paths: '{''root_dir'': ''${oc.env:PROJECT_ROOT}'', ''data_dir'': ''BEAT_dataset/beat_english_v0.2.1'',
      ''data_dir_test'': ''New_bvh_dataset'', ''log_dir'': ''./logs/'', ''output_dir'':
      ''${hydra:runtime.output_dir}'', ''work_dir'': ''${hydra:runtime.cwd}''}'
    seed: '1234'
    tags:
    - dev
    task_name: test
    test: 'True'
    train: 'False'
    trainer: '{''_target_'': ''lightning.pytorch.trainer.Trainer'', ''default_root_dir'':
      ''${paths.output_dir}'', ''min_epochs'': 1, ''max_epochs'': 300, ''accelerator'':
      ''gpu'', ''devices'': 1, ''precision'': 16, ''check_val_every_n_epoch'': 1,
      ''deterministic'': False}'
    wandb_project: test_video
_flags_cache:
  desc: null
  value:
    convert: null
    struct: true
_metadata:
  desc: null
  value: 'ContainerMetadata(ref_type=typing.Any, object_type=<class ''dict''>, optional=True,
    key=None, flags={''struct'': True}, flags_root=False, resolver_cache=defaultdict(<class
    ''dict''>, {''now'': {(''%Y-%m-%d'',): ''2024-07-29'', (''%H-%M-%S'',): ''13-33-25''}}),
    key_type=typing.Any, element_type=typing.Any)'
_parent:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: huggingface
    huggingface_version: 4.42.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.19
    start_time: 1722227607.615099
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 50
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.8.19
      5: 0.13.11
      6: 4.42.4
      8:
      - 3
      - 5
callbacks:
  desc: null
  value:
    early_stopping:
      _target_: lightning.pytorch.callbacks.EarlyStopping
      check_finite: true
      check_on_train_epoch_end: null
      divergence_threshold: null
      min_delta: 0.0
      mode: min
      monitor: val_loss
      patience: 300
      stopping_threshold: null
      strict: true
      verbose: false
    model_checkpoint:
      _target_: lightning.pytorch.callbacks.ModelCheckpoint
      auto_insert_metric_name: false
      dirpath: ${paths.output_dir}/checkpoints
      every_n_epochs: null
      every_n_train_steps: null
      filename: epoch_{epoch:03d}
      mode: min
      monitor: val_loss
      save_last: true
      save_on_train_epoch_end: null
      save_top_k: 3
      save_weights_only: false
      train_time_interval: null
      verbose: false
    model_summary:
      _target_: lightning.pytorch.callbacks.RichModelSummary
      max_depth: -1
    rich_progress_bar:
      _target_: lightning.pytorch.callbacks.RichProgressBar
ckpt_path:
  desc: null
  value: D:/motion-tokenizer/logs/train/runs/2024-07-25_15-12-57/checkpoints/epoch_003.ckpt
data:
  desc: null
  value:
    _target_: src.data.gesture_datamodule.MotionDataModule
    batch_size: 1
    data_norm_stat_path: data/motion_data_stat.npy
    dataset_name: beat
    motion_fps: 15
    motion_type: bvh
    n_joints: 73
    n_poses: 128
    n_preposes: 32
    normalization_method: mean-std
    num_workers: 0
    pin_memory: false
    pose_dim: 657
    raw_data_path: ${paths.data_dir_test}
    test_dir: new_data/lmdb_test
    train_dir: new_data/lmdb_train
    use_weighted_sampler: false
    val_dir: new_data/lmdb_val
extras:
  desc: null
  value:
    enforce_tags: true
    ignore_warnings: false
    print_config: true
model:
  desc: null
  value:
    _target_: src.models.vae_module.VQVaeLitModel
    activation: relu
    code_dim: 512
    code_num: 256
    commit: 0.02
    data_norm_stat_path: ${data.data_norm_stat_path}
    depth: 3
    dilation_growth_rate: 3
    down_t: 3
    loss_vel_factor: 0.5
    nb_joints: ${data.n_joints}
    nfeats: ${data.pose_dim}
    norm: None
    normalization_method: ${data.normalization_method}
    optimizer_cfg:
      params:
        betas:
        - 0.9
        - 0.99
        lr: 0.0002
        weight_decay: 0.0
      target: torch.optim.AdamW
    output_emb_width: 512
    quantizer: ema_reset
    recons_loss: l1_smooth
    scheduler_cfg:
      params:
        T_max: 100
        eta_min: 1.0e-06
      target: torch.optim.lr_scheduler.CosineAnnealingLR
    stride_t: 2
    width: 512
model/params/non_trainable:
  desc: null
  value: 0
model/params/total:
  desc: null
  value: 28781201
model/params/trainable:
  desc: null
  value: 28781201
seed:
  desc: null
  value: 1234
tags:
  desc: null
  value:
  - dev
task_name:
  desc: null
  value: test
trainer:
  desc: null
  value:
    _target_: lightning.pytorch.trainer.Trainer
    accelerator: gpu
    check_val_every_n_epoch: 1
    default_root_dir: ${paths.output_dir}
    deterministic: false
    devices: 1
    max_epochs: 300
    min_epochs: 1
    precision: 16
