_target_: src.models.vae_module.VQVaeLitModel

# optimizer:
#   lr: 5e-4

# model_args:
#   codebook_size: 8192
#   embed_dim: 32
#   z_channels: 32
#   resolution: 64
#   in_channels: ${data.pose_dim}
#   out_ch: ${data.pose_dim}
#   ch: 64
#   ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
#   num_res_blocks: 2
#   attn_resolutions: [ 16 ]
#   dropout: 0.0
#   entropy_loss_weight: 0.02
#   norm: 'LN'

# n_poses: ${data.n_poses}
# pose_dim: ${data.pose_dim}
# nfeats: ${data.pose_dim} # pose_dim
# motion_fps: ${data.motion_fps}
# n_joints: ${data.n_joints}
# data_norm_stat_path: ${data.data_norm_stat_path}
# normalization_method: ${data.normalization_method}

nfeats: ${data.pose_dim}
quantizer: "ema_reset"
code_num: 512
code_dim: 512
output_emb_width: 512
down_t: 3
stride_t: 2
width: 512
depth: 3
dilation_growth_rate: 3
norm: None
activation: "relu"