# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
beat_data_dir: BEAT_dataset/Beat_dataset
aihub_data_dir: AIHUB_DATA
data_dir_test: single_bvh_test

pkl_path: "E:/data/pkl/XXXXXXXXX.pkl" # XXXXXXXXX will be the name of the bvh file, dynamically generated during the run
out_bvh_path: "E:/data/processed_bvh/XXXXXXXXX.bvh"

# path to logging directory
log_dir: ./logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
