# @package _global_

defaults:
  - _self_
  - data: beat.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null


hydra/job_logging: disabled
hydra/hydra_logging: disabled

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: null
