# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: beat_test.yaml
  - model: vqvae.yaml
  - callbacks: default.yaml
  - logger: many_loggers.yaml # set logger here or use command line (e.g. `python test.py logger=tensorboard`)
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default.yaml

  # debugging config (enable through command line, e.g. `python test.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "test"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python test.py tags="[first_tag, second_tag]"`
tags: ["dev"]

# set False to skip model training
train: False

# evaluate on test set, using specified model weights
test: True

# provide checkpoint path for testing
ckpt_path: "D:\\motion-tokenizer\\logs\\train\\runs\\2024-07-26_13-51-29\\checkpoints\\last.ckpt"

wandb_project: "motion-tokenizer_test"


# seed for random number generators in pytorch, numpy and python.random
seed: 1234


